startport: 8080
monitors: 3
pages:
  index:
    time: 5
  hej:
    time: 5
  bruh:
    time: 5
setmonitors:
  "8080":
    showpages:
      - bruh
      - hej
  "8081":
    showpages:
      - bruh
  "8082":
    showpages: []
